---
- name: install python dev
  apt: name=python-dev
- name: install python setup tools
  apt: name=python-setuptools
- name: install pip
  easy_install: name=pip
- name: install requests
  pip: name=requests
- name: install flask
  pip: name=flask
- name: install flask-runner
  pip: name=flask-runner
- name: install netifaces
  pip: name=netifaces
- name: install tweepy
  pip: name=tweepy
- name: install couchdb
  pip: name=couchdb
- name: install textblob
  pip: name=textblob
- name: install web
  pip: name=web.py

- name: ensure deploy directory
  file: path=/opt/deploy state=directory
- name: ensure deploy cwd directory
  file: path=/opt/deploy/cwd state=directory owner=ubuntu

- name: ensure environment variables
  template: src=env.j2 dest=/etc/profile.d/app-env.sh

- name: install applications
  synchronize: src=../templates/ dest=/opt/deploy/
  notify: restart apps
- name: configure applications
  template: src=init.j2 dest=/etc/init.d/{{item.name}} mode=0755
  with_items: apps
  notify: restart apps
- name: establish app services
  service: name={{item.name}} state=started
  with_items: apps
