---
- name: install httplib2
  apt: name=python-httplib2
- name: create twitter database
  uri: 
    url=http://localhost:5984/twitter
    method=PUT
    status_code=200,201,202,412
- name: handle twitter replication
  uri: 
    url=http://localhost:5984/_replicate
    method=POST
    body='{"source":"twitter","target":"http://{{ item }}:5984/twitter","continuous":true}'
    HEADER_Content-Type="application/json"
    status_code=200,201,202,412
  with_items: "{{ groups[peer_group] | difference([inventory_hostname]) }}"
