---
- name: establish haproxy repository
  apt_repository: repo=ppa:vbernat/haproxy-1.5 update_cache=yes state=present
- name: install haproxy
  apt: name=haproxy
- name: configure haproxy
  notify: restart haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
- name: configure monit for application
  template: src=monit.j2 dest=/etc/monit/conf.d/haproxy mode=0644
  notify: reload monit
- name: establish service
  service: name=haproxy state=started
