---
- name: configure chirp nodes
  hosts: chirp
  sudo: yes
  roles:
    - role: chirp-persist-vol
    - role: ansible-couchdb-peruser
    - role: chirp-couchdb
    - role: geerlingguy.apache
    - role: ANXS.monit
    - role: chirp-haproxy
    - role: chirp-apps
    - role: ansible-elasticsearch
    - role: logstash-role
    - role: azavea.kibana
