---
- name: configure chirp nodes
  hosts: chirp
  sudo: yes
  pre_tasks:
    # - name: wait for SSH to load
    #   local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10 timeout=600
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - role: chirp-persist-vol
    - role: ansible-couchdb-peruser
    - role: chirp-couchdb
    - role: geerlingguy.apache
    - role: ANXS.monit
    # - role: ansible-elasticsearch
    # - role: logstash-role
    # - role: azavea.kibana
    - role: chirp-apps
    - role: chirp-haproxy
    - role: chirp-monit
