---
- hosts: all

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.elasticsearch", elasticsearch_version: "1.4.4" }
    - { role: "azavea.logstash" }
    - { role: "azavea.kibana", elasticsearch_cluster_name: "logstash" }

  tasks:
    - name: Add Logstash user to service group
      user: name=logstash
            append=yes
            groups=adm
            state=present

    - name: Configure Logstash
      template: src=templates/logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf
      notify:
        - Restart Logstash
