---
twitter:
  consumer_key: "RWG77BWeRymf1FoFWIKZjigli"
  consumer_secret: "TDyQCxKxB9o5zxIe9WCQETy3Paw8T57DuBB772SA5WZYqOIUSL"
  access_token: "22651013-tL49l2oBX7ooochixyuzkTqhJBbJbq2oVrDSuEYlB"
  access_token_secret: "oZojkB9n9RP0hf4cfgdVoDT7bHZKbtTkavVPTJxSXxgHr"
  harvest_mode: "CITY"
