---
twitter:
  consumer_key: "8w5xQbiWoLlC9eNYAZt6qBb3i"
  consumer_secret: "L4h4ArOMalcdIYEg62QAWVHSLe75RiaxApZzYjelMjjmd3dXtG"
  access_token: "580647653-1MLL52CT6mwBpviA9irw7wgz0z23J3F7wG8Dra1J"
  access_token_secret: "1bC7wFvhDHYg6SKiQKrwDkT5sKmgHPg8UCHzuf6MnNclk"
